name: Deploy 📦 to Test-Pypi and Pypi 🐍

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install TensorLy and TensorLy-Torch dev
        run: |
          git clone https://github.com/tensorly/tensorly
          cd tensorly
          python -m pip install -e .
          cd ..
          git clone https://github.com/tensorly/torch
          cd torch
          python -m pip install -e .
          cd ..
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
      - name: Install package
        run: |
          python -m pip install -e .
          pip install setuptools wheel
      - name: Build a binary wheel and a source tarball
        run: |
          python setup.py sdist bdist_wheel
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/<package-name>  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
